FROM rust:1.65-bullseye as builder
WORKDIR /usr/src/app
# https://users.rust-lang.org/t/cargo-uses-too-much-memory-being-run-in-qemu/76531
ENV CARGO_NET_GIT_FETCH_WITH_CLI=true
RUN apt-get update && apt-get install -y libpq-dev && rm -rf /var/lib/apt/lists/*
RUN cargo install diesel_cli --no-default-features --features postgres
ENTRYPOINT ["./dev.sh" ]
