FROM rust:1.60-slim-bullseye as builder
WORKDIR /usr/src/app
RUN apt-get update && apt-get install -y libpq-dev && rm -rf /var/lib/apt/lists/*
RUN cargo install diesel_cli --no-default-features --features postgres
ENTRYPOINT ["./dev.sh" ]