services:
  cockroach-ci:
    image: cockroachdb/cockroach:v23.2.4
    command: start-single-node --insecure
    restart: unless-stopped
    network_mode: host
  cockroach:
    image: cockroachdb/cockroach:v23.2.4
    command: start-single-node --insecure
    restart: unless-stopped
    ports:
      - 8080:8080
      - 26257:26257
  tira:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app/
    command:
      [
        "sh",
        "-c",
        "sqlx database create && sqlx migrate run && psql -h cockroach -p 26257 -U root -v ON_ERROR_STOP=on -f insert_test_users.sql tira && cargo run",
      ]
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - cockroach
    restart: unless-stopped
