name: Rust

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Repo metadata
        id: repo
        uses: actions/github-script@v3
        with:
          script: |
            const repo = await github.repos.get(context.repo)
            return repo.data
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Dispatch build to kaniko.jrcichra.dev
        id: dispatch
        uses: jrcichra/kaniko-dispatcher@main
        with:
          name: tira-backend
          url: https://kaniko.jrcichra.dev
          context: "git://github.com/tjcichra/tira-backend#${{ github.sha }}"
          destination: "ghcr.io/tjcichra/tira_backend:sha-${{ steps.vars.outputs.sha_short }}-amd64"
          secret: tim-ghcr-io
          arch: amd64
          build-args: |
            {
              "RUSTC_WRAPPER" : "/usr/local/bin/sccache",
              "SCCACHE_BUCKET": "sccache",
              "AWS_ACCESS_KEY_ID": "github",
              "AWS_SECRET_ACCESS_KEY": "${{ secrets.AWS_SECRET_ACCESS_KEY }}",
              "SCCACHE_ENDPOINT": "http://minio.minio:9000"
            }
          headers: |
            {
              "CF-Access-Client-Id" : "46ea1be6ad585778416864f114d5cff1.access",
              "CF-Access-Client-Secret" : "${{ secrets.ORACLE_K8S_ACCESS_TOKEN }}"
            }
  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Repo metadata
        id: repo
        uses: actions/github-script@v3
        with:
          script: |
            const repo = await github.repos.get(context.repo)
            return repo.data
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Dispatch build to kaniko.jrcichra.dev
        id: dispatch
        uses: jrcichra/kaniko-dispatcher@main
        with:
          name: tira-backend
          url: https://kaniko.jrcichra.dev
          context: "git://github.com/tjcichra/tira-backend#${{ github.sha }}"
          destination: "ghcr.io/tjcichra/tira_backend:sha-${{ steps.vars.outputs.sha_short }}-arm64"
          secret: tim-ghcr-io
          arch: arm64
          build-args: |
            {
              "SCCACHE_BUCKET": "sccache",
              "AWS_ACCESS_KEY_ID": "github",
              "AWS_SECRET_ACCESS_KEY": "${{ secrets.AWS_SECRET_ACCESS_KEY }}",
              "SCCACHE_ENDPOINT": "http://minio.minio:9000"
            }
          headers: |
            {
              "CF-Access-Client-Id" : "46ea1be6ad585778416864f114d5cff1.access",
              "CF-Access-Client-Secret" : "${{ secrets.ORACLE_K8S_ACCESS_TOKEN }}"
            }

  combine-manifests:
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Repo metadata
        id: repo
        uses: actions/github-script@v3
        with:
          script: |
            const repo = await github.repos.get(context.repo)
            return repo.data
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: tjcichra
          password: ${{ secrets.GHCR_SECRET }}
      - name: Combine manifests
        run: .github/build/manifest.sh
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          TIRA_SHA: ${{ github.sha }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
